In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [5]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [13]:
X = digits.data
X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [14]:
y = digits.target
y

array([0, 1, 2, ..., 8, 9, 8])

In [19]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=10000)

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [21]:
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [22]:
lr.score(X_test, y_test)

0.9611111111111111

In [24]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [25]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [26]:
rf.score(X_test, y_test)

0.9722222222222222

In [28]:
from sklearn.svm import SVC
sv = SVC(Q)

In [29]:
sv.fit(X_train, y_train)

SVC()

In [30]:
sv.score(X_test, y_test)

0.9861111111111112

In [31]:
'''In all the above three machine learning models the data was split not uniformly between the train and the test data.
And everytime we run the function train_test_split the prediction models output also varies. This is the reason we use K Fold Cross Validation'''

'In all the above three machine learning models the data was split not uniformly between the train and the test data.\nAnd everytime we run the function train_test_split the prediction models output also varies. This is the reason we use K Fold Cross Validation'

In [36]:
'''KFold cross validation'''
from sklearn.model_selection import KFold
Kf = KFold(n_splits = 3)
Kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [38]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

                                    

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [53]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver='lbfgs',multi_class='auto', max_iter=10000), X, y, cv = 3)

array([0.92487479, 0.94156928, 0.92320534])

In [60]:
cross_val_score(SVC(kernel='rbf',degree=3), X, y, cv = 3)

array([0.96494157, 0.97996661, 0.96494157])

In [57]:
score1 = cross_val_score(LogisticRegression(solver='lbfgs',multi_class='auto', max_iter=10000), X, y, cv = 3)

In [59]:
np.average(score1)

0.9298831385642737

In [61]:
score2 = cross_val_score(SVC(kernel='rbf',degree=3), X, y, cv = 3)
np.average(score2)

0.9699499165275459